[client]
showErrorDetails = "full"
toolbarMode = "auto"
showSidebarNavigation = true

[server]
headless = true

[theme]
base = "dark"
primaryColor = "#03045e"
backgroundColor = "#e0fbfc"
secondaryBackgroundColor = "#02c39a"
textColor = "#212529"
font = "sans-serif"
headingFont = "sans-serif"
headingFontSizes = [
    "2.75rem",
    "2.25rem",
    "1.75rem",
    "1.5rem",
    "1.25rem",
    "1rem"
]
headingFontWeights = [
    700,
    600,
    600,
    600,
    600,
    600
]