"""Represents the Symptoms model for storing patient symptoms in the database."""
from sqlalchemy import Boolean, Column, Integer

from apis.db.database import Base


class Symptom(Base):
    """Stores patient symptoms in the database."""
    __tablename__ = 'symptoms'

    patient_id = Column(Integer, primary_key=True, index=True)

    abdominal_pains = Column(Boolean, nullable=False)
    acholic_stool = Column(Boolean, nullable=False)
    anorexia = Column(Boolean, nullable=False)
    arthralgia = Column(Boolean, nullable=False)
    back_pain = Column(Boolean, nullable=False)
    blurred_vision = Column(Boolean, nullable=False)
    bradycardia = Column(Boolean, nullable=False)
    chest_pain = Column(Boolean, nullable=False)
    chills_and_rigors = Column(Boolean, nullable=False)
    choluria = Column(Boolean, nullable=False)
    confusion_altered_mental_status = Column(Boolean, nullable=False)
    constipation = Column(Boolean, nullable=False)
    cough = Column(Boolean, nullable=False)
    dehydration = Column(Boolean, nullable=False)
    diarrhea = Column(Boolean, nullable=False)
    dizziness = Column(Boolean, nullable=False)
    dyspnea_wheezing_respiratorydistress = Column(Boolean, nullable=False)
    edema = Column(Boolean, nullable=False)
    eschar = Column(Boolean, nullable=False)
    eye_symptoms_conjunctivitis_conjunctival_suffusion = Column(
        Boolean, nullable=False)
    facial_redness = Column(Boolean, nullable=False)
    fatigue = Column(Boolean, nullable=False)
    headache = Column(Boolean, nullable=False)
    hematemesis = Column(Boolean, nullable=False)
    hematuria = Column(Boolean, nullable=False)
    hemoptysis = Column(Boolean, nullable=False)
    hemorrhage = Column(Boolean, nullable=False)
    hepatomegaly = Column(Boolean, nullable=False)
    itching = Column(Boolean, nullable=False)
    jaundice = Column(Boolean, nullable=False)
    lethargy_drowsiness = Column(Boolean, nullable=False)
    lymphadenopathy = Column(Boolean, nullable=False)
    lymphangitis = Column(Boolean, nullable=False)
    melena = Column(Boolean, nullable=False)
    mouth_ulcers = Column(Boolean, nullable=False)
    mucosal_bleeding = Column(Boolean, nullable=False)
    myalgia = Column(Boolean, nullable=False)
    nausea = Column(Boolean, nullable=False)
    oliguria = Column(Boolean, nullable=False)
    petechia = Column(Boolean, nullable=False)
    pneumonia = Column(Boolean, nullable=False)
    positive_tourniquet_test = Column(Boolean, nullable=False)
    prostration = Column(Boolean, nullable=False)
    purpura = Column(Boolean, nullable=False)
    rash = Column(Boolean, nullable=False)
    retro_orbital_pain = Column(Boolean, nullable=False)
    rhinorrhea = Column(Boolean, nullable=False)
    seizures = Column(Boolean, nullable=False)
    shock = Column(Boolean, nullable=False)
    sore_throat = Column(Boolean, nullable=False)
    splenomegaly = Column(Boolean, nullable=False)
    tachycardia = Column(Boolean, nullable=False)
    vomiting = Column(Boolean, nullable=False)
    weakness_malaise = Column(Boolean, nullable=False)
