CREATE table patients(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    age INTEGER NOT NULL,
    sex TEXT NOT NULL,
    race TEXT,
    date TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS symptoms (
    patient_id INTEGER NOT NULL,
    abdominal_pains BOOLEAN NOT NULL,
    acholic_stool BOOLEAN NOT NULL,
    anorexia BOOLEAN NOT NULL,
    arthralgia BOOLEAN NOT NULL,
    back_pain BOOLEAN NOT NULL,
    blurred_vision BOOLEAN NOT NULL,
    bradycardia BOOLEAN NOT NULL,
    chest_pain BOOLEAN NOT NULL,
    chills_and_rigors BOOLEAN NOT NULL,
    choluria BOOLEAN NOT NULL,
    confusion_altered_mental_status BOOLEAN NOT NULL,
    constipation BOOLEAN NOT NULL,
    cough BOOLEAN NOT NULL,
    dehydration BOOLEAN NOT NULL,
    diarrhea BOOLEAN NOT NULL,
    dizziness BOOLEAN NOT NULL,
    dyspnea_wheezing_respiratorydistress BOOLEAN NOT NULL,
    edema BOOLEAN NOT NULL,
    eschar BOOLEAN NOT NULL,
    eye_symptoms_conjunctivitis_conjunctival_suffusion BOOLEAN NOT NULL,
    facial_redness BOOLEAN NOT NULL,
    fatigue BOOLEAN NOT NULL,
    headache BOOLEAN NOT NULL,
    hematemesis BOOLEAN NOT NULL,
    hematuria BOOLEAN NOT NULL,
    hemoptysis BOOLEAN NOT NULL,
    hemorrhage BOOLEAN NOT NULL,
    hepatomegaly BOOLEAN NOT NULL,
    itching BOOLEAN NOT NULL,
    jaundice BOOLEAN NOT NULL,
    lethargy_drowsiness BOOLEAN NOT NULL,
    lymphadenopathy BOOLEAN NOT NULL,
    lymphangitis BOOLEAN NOT NULL,
    melena BOOLEAN NOT NULL,
    mouth_ulcers BOOLEAN NOT NULL,
    mucosal_bleeding BOOLEAN NOT NULL,
    myalgia BOOLEAN NOT NULL,
    nausea BOOLEAN NOT NULL,
    oliguria BOOLEAN NOT NULL,
    petechia BOOLEAN NOT NULL,
    pneumonia BOOLEAN NOT NULL,
    positive_tourniquet_test BOOLEAN NOT NULL,
    prostration BOOLEAN NOT NULL,
    purpura BOOLEAN NOT NULL,
    rash BOOLEAN NOT NULL,
    retro_orbital_pain BOOLEAN NOT NULL,
    rhinorrhea BOOLEAN NOT NULL,
    seizures BOOLEAN NOT NULL,
    shock BOOLEAN NOT NULL,
    sore_throat BOOLEAN NOT NULL,
    splenomegaly BOOLEAN NOT NULL,
    tachycardia BOOLEAN NOT NULL,
    vomiting BOOLEAN NOT NULL,
    weakness_malaise BOOLEAN NOT NULL
);